### ISSUE TITLE
Define styling guidelines for all charts

### ISSUE THREAD

**Issue by arouault** [MAPC/datacommon#105]
Create the visual rules for charts. Put examples here!

**Comment by jdev42092** [comment]
Here are the colors that I had scoped out (and checked for B+W Printing, Color Blindness):  

Primary = ['#1F4F43', '#2A9979', '#79BF60', '#283b5d']
![screen shot 2018-08-01 at 12 01 17 pm](https://user-images.githubusercontent.com/16709472/43533481-e3c3e480-9582-11e8-8a14-1d1c1af8308d.png)
Secondary = ['#1F5E99', '#727878', '#FFB6C1']
![screen shot 2018-08-01 at 12 02 13 pm](https://user-images.githubusercontent.com/16709472/43533482-e3d30a28-9582-11e8-9d6f-b88753aa359c.png)
Highlights = ['#FFD93A', '#C7493E']
![screen shot 2018-08-01 at 12 02 48 pm](https://user-images.githubusercontent.com/16709472/43533483-e3e16d2a-9582-11e8-8f00-755222a26a6c.png)

**Comment by deedeekim** [comment]
The XD file is on the server with the latest chart styles: DataCommon_080318_DK
![screen shot 2018-08-03 at 11 05 08 am](https://user-images.githubusercontent.com/25641695/43650177-1c7781ac-970d-11e8-9aa6-7c0561f5a1cf.png)
