### ISSUE TITLE
Login Button Should be Hidden

### ISSUE THREAD

**Issue by mzagaja** [MAPC/datacommon#109]
**Describe the bug**
A login bug (reserved for future design iterations) is present on the staging website.

**Steps to reproduce**
Walk us through how you revealed the bug.
1. Go to http://staging.datacommon.mapc.org/
2. Notice the login button

**Expected behavior**
There should not be a login button since we do not have a login feature.

**Screenshots**
![screen shot 2018-08-01 at 4 57 05 pm](https://user-images.githubusercontent.com/565647/43548478-f7f50834-95ab-11e8-8b10-a751b5b0fffa.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 11.1.2

**Comment by iangmhill** [comment]
- [ ] Make nav bar mobile responsive (including login button)
