### ISSUE TITLE
"Data not available" tag needed when data is missing

### ISSUE THREAD

**Issue by jdev42092** [MAPC/datacommon#158]
When data is missing, graphs are currently rendering as empty. There should be something to indicate that the data is missing and it's not an issue with the chart not rendering correctly.

**Comment by theryankelly** [comment]
I believe Hampden's Water Usage per Capita [is a case](https://staging.datacommon.mapc.org/profile/hampden/environment) where this is happening. 

![image](https://user-images.githubusercontent.com/2421382/95381218-d3c5f200-08b5-11eb-89fd-351e54d02f1d.png)
