### ISSUE TITLE
Chatham breaks Community Profiles page

### ISSUE THREAD

**Issue by ericyoungberg** [MAPC/datacommon#164]
**Describe the bug**
When navigating to [Chatham](https://staging.datacommon.mapc.org/profile/chatham/demographics), the application breaks. This may be happening for other munis but we won't know until we find them.

**Steps to reproduce**
1. Navigate to any Chatham Community Profile tab using either the URL or the community search bar at the bottom of the home page.

**Expected behavior**
It should pull in and display the data like all of the rest of the Community Profile pages.

**Comment by deedeekim** [comment]
So does Hull!
