### ISSUE TITLE
Change button labels 

### ISSUE THREAD

**Issue by arouault** [MAPC/datacommon#166]
- [ ] Metadata button should read "Metadata" not 'meta' 

- [ ] It is common to swap in xls or "Excel" in lieu of .csv for non-technical audiences who may want to download data. I would advise changing CSV to XLS or providing some helper text. 

![screen shot 2018-08-28 at 12 10 56 pm](https://user-images.githubusercontent.com/1305629/44735822-83b3b900-aabb-11e8-83e2-4cb4a90ca09b.png)

**Comment by mzagaja** [comment]
First one should be easy to do.

On the second one, although I see where you are coming from, I disagree with changing csv to xls. Doing so would be the equivalent of serving someone tea when they asked for coffee. While it might be a caffeinated warm beverage, they won’t be getting it in the format they expect.
