### ISSUE TITLE
Data Error with Land Line .shp file

### ISSUE THREAD

**Issue by theryankelly** [MAPC/datacommon#209]
**Describe the bug**
User downloaded the .shp from https://datacommon.mapc.org/browser/datasets/357 (Land Line Systems (Lines)).  When loaded in QGIS, nothing appears, even though the file size suggests that there’s data there. 

Downloading the .shp Bicycle Facilities (https://datacommon.mapc.org/browser/datasets/356) worked fine.  

Error when opening the file in ArcMap “Open Failed --> Error opening feature class --> Number of shapes does not match the number of table records”"

**Steps to reproduce**
Walk us through how you revealed the bug.
1. Go to https://datacommon.mapc.org/browser/datasets/357
2. Click on .shp download button
3. Open in QGIS or ArcMap

**Expected behavior**
Expect a full data file

**Comment by mzagaja** [comment]
This was a botched export and was fixed by deleting the cache and re-requesting the file. It should work going forward.

![image](https://user-images.githubusercontent.com/565647/53753913-74556400-3e80-11e9-935c-b1f1f7083a91.png)
