### ISSUE TITLE
Add Google Analytics Event Tracker to Download Link

### ISSUE THREAD

**Issue by mzagaja** [MAPC/datacommon#218]
**Describe the feature. What should a user be able to do?**
Google analytics should trigger an event when a user clicks a download link.

**Why do we need this feature?**
This would allow us to track downloads of datasets as opposed to visits to the dataset page.

**Comment by atomtay** [comment]
I wonder if a similar pipeline could be applied to the "Click to download and explore data" in the legend of most calendar visualizations; could we track the full conversion from viewing the viz > viewing the data > downloading the data?
