### ISSUE TITLE
Spelling Mistake Transportation

### ISSUE THREAD

**Issue by theryankelly** [MAPC/datacommon#222]
Two instances of "Transportation being misspelled. "Tranportation" instead of "Transportation" in subtopic listing.
https://datacommon.mapc.org/browser/Transportation

![Screen Shot 2019-11-22 at 2 43 10 PM](https://user-images.githubusercontent.com/2421382/69455529-9789b180-0d36-11ea-87b2-b4ccb17a1313.png)

Should check other instances of the word and fix an other misspellings

**Comment by theryankelly** [comment]
Still an issues when checking today.

<img width="357" alt="Screen Shot 2019-11-29 at 1 01 01 PM" src="https://user-images.githubusercontent.com/2421382/69884872-6cf4a700-12a8-11ea-947a-8cd4ab6474c2.png">

**Comment by mzagaja** [comment]
The search feature didn't surface these on the Table until I searched for the full phrases, should be set now.
