### ISSUE TITLE
Fix Geospatial Metadata Download

### ISSUE THREAD

**Issue by mzagaja** [MAPC/datacommon#250]
**Describe the bug**
Sometimes the geospatial metadata downloads as empty values. It is pointing to the incorrect part of the XML. Look at for example the Land Parcel Database.

**Additional context**
> Matt Zagaja 3:41 PM
It’s the XML from the gdb_items table in the sde schema of the gisdata database on db.live.mapc.org and looks at the definition column for the XML. The key values its looking at are defined by name: column.attrlabel, alias: column.attalias, details: column.attrdef and its looking in the path of metadata['documentation']['metadata']['eainfo']['detailed']['attr']

**Comment by mzagaja** [comment]
![image](https://user-images.githubusercontent.com/565647/73190993-c9cbdc80-40f4-11ea-94e2-a81f835e81e1.png)
 Edge case to explore above.

**Comment by mzagaja** [comment]
On staging https://staging.datacommon.mapc.org/browser/datasets/390 seems to not work for metadata download. Town Data related metadata seems to download ok.

**Comment by theryankelly** [comment]
#174 related
