### ISSUE TITLE
Mocks for All Major Pages

### ISSUE THREAD

**Issue by mzagaja** [MAPC/datacommon#3]

**Comment by arouault** [comment]
@ericyoungberg please upload your most recent mockups here and we can close out?

**Comment by iangmhill** [comment]
@deedeekim Could you upload the most recent mock-ups and close this issue.

**Comment by deedeekim** [comment]
[DataCommon_080318_DK.pdf](https://github.com/MAPC/datacommon/files/2287274/DataCommon_080318_DK.pdf)
