### ISSUE TITLE
Shapefile download of walking trails incorrect

### ISSUE THREAD

**Issue by atomtay** [MAPC/datacommon#304]
**Describe the bug**
The Shapefile download for the [Walking Trails](https://datacommon.mapc.org/browser/datasets/382) does not display correctly in mapping applications like QGIS, ArcMap, and [mapshaper](https://mapshaper.org/).

**Steps to reproduce**
1. Go to [Walking Trails](https://datacommon.mapc.org/browser/datasets/382) on Datacommon
2. Click to 'shp' button to download the Shapefile
3. Unzip .zip file and open Shapefile in mapping application
4. Depending on the mapping application, you'll either not see anything or be given an error while opening the file. For example, in QGIS the file will open, but when you click "Feature Count" it lists 0 features.

**Expected behavior**
You should see the line data for the walking trails in your mapping application. It should look like the Paved Footways and Natural Surface Footways layers on [Trailmap](https://trailmap.mapc.org/)

**Screenshots**
Error message from ArcMap:
![image](https://user-images.githubusercontent.com/10645500/83154980-be9eb280-a0ce-11ea-9b80-d81f1977b9f4.png)

Error message from MapShaper:
![Screen Shot 2020-05-28 at 10 34 16 AM](https://user-images.githubusercontent.com/10645500/83155038-d2e2af80-a0ce-11ea-9de4-e83a5db6e393.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 10.15.4
 - Browser: Firefox
 - Version: 76.0.1

**Additional context**
The feature class in the database appears to be fine, so this is likely a download issue. Additionally, downloading the CSV seems to work as expected.

**Comment by mzagaja** [comment]
Potentially related to #306

**Comment by mzagaja** [comment]
Now working for me after implementing fix for #306 
![image](https://user-images.githubusercontent.com/565647/83445233-a0acb700-a41a-11ea-964b-4b0a386772e3.png)

**Comment by mzagaja** [comment]
Closing this since it appeared to be fixed and I can no longer replicate it.
