### ISSUE TITLE
Count of datasets displayed in "Popular Datasets" doesn't match count of datasets available.

### ISSUE THREAD

**Issue by theryankelly** [MAPC/datacommon#354]
Example Education list "15 Datasets", when only two appear in selection.

![education datacommon selection](https://user-images.githubusercontent.com/2421382/96599513-01e80080-12be-11eb-9a39-059e8e678887.PNG)

Related to #213

**Comment by mzagaja** [comment]
I started digging into this, but am failing to reproduce it on production or on the `dev` branch.

datacommon.mapc.org in Chome:
![image](https://user-images.githubusercontent.com/565647/96911506-ebcd7200-146e-11eb-9262-2599ac50d74b.png)

Can you confirm it's still happening and if so try doing a full cache clear (CMD+Opt+R) and check a separate browser to see if it might be browser or cache specific?

**Comment by mzagaja** [comment]
oh wait, I did not see in the first screenshot it was popular datasets. I was trying "education" from the first menu. I see it now.
