### ISSUE TITLE
DataCommon Cannot Serve Housing Submarkets Data

### ISSUE THREAD

**Issue by mzagaja** [MAPC/datacommon#376]
**Describe the bug**
DataCommon currently cannot serve the data from

```sql
SELECT
	muni
FROM
	tabular.hous_submarkets_ct
LIMIT 15000;
```

Despite the fact it has permissions to do so via the viewer account.

**Steps to Reproduce**
1. Go to https://datacommon.mapc.org/browser/datasets/422
2. See it fail to load.

**Other Troubleshooting Steps**
1. Validated I can query the DB using viewer from TablePlus with the query and return the full list of useful results.

Confirmed the issue that running:
```sh
curl "https://prql.mapc.org/?token=96608389a2545f7adac815ea258ad27e&query=SELECT%20*i%20FROM%20tabular.hous_submarkets_ct%20LIMIT%2015000"
```
returns an empty body.
3. Reviewed the PRQL log on prql.mapc.org (accessible after logging in with ubuntu@prql.mapc.org ) with the following command:
```sh
sudo cat /var/lib/prql/access.log | grep -A2 -B2 'hous_submarkets_ct'
```
And saw no errors thrown.

4. Confirmed if I constrain the request to PRQL to `SELECT muni FROM …` it will return useful data in the body.

This seems to be strong evidence (as Annabelle noted earlier) that there is a bug in PRQL land. I think the options are to run a differential removal of the columns until we can identify which one is causing the hiccup and then leaving that column out  of the final dataset, or we will have to learn the Go programming language so we can debug PRQL.

**Comment by atomtay** [comment]
From @hydrickg on Slack:

> queried all of the columns yesterday, which indicated Infinity values in 3 columns as the problem. These were all margin of error percentage columns, with the corresponding column value of 0. I updated the 28 Infinity values to 0, and the table now loads correctly.

Can confirm that the dataset loads properly on [Datacommon](https://datacommon.mapc.org/browser/datasets/422), so closing this and the corresponding cross-posted issue on Housing Submarkets.
