### ISSUE TITLE
JAN Viz label contrast

### ISSUE THREAD

**Issue by theryankelly** [MAPC/datacommon#377]
**Describe the bug**
The JAN label is hard to read. Can we switch the text when updating next month to the dark green (#03332D I believe)?

![image](https://user-images.githubusercontent.com/2421382/109167111-696dfb00-774b-11eb-8327-860ef4e2ad26.png)

**Where**
Home back gallery image

**Desktop (please complete the following information):**
 - Windows
 - Chrome

**Comment by atomtay** [comment]
It's up on staging and will go live when we push the March calendar on Monday.
