### ISSUE TITLE
Join Metadata to Dataset on Front End

### ISSUE THREAD

**Issue by mzagaja** [MAPC/datacommon#39]
As a user in the data library I should be able to see metadata for the data set I am looking at. The data library should pull and display the appropriate metadata for the dataset.

**Comment by mzagaja** [comment]
Note that for this to properly work due to the fact that failed syncs will sometimes cause a dataset to sync to Carto with the table name + an underscore and a number you'll need to regex for that for possible joins.

**Comment by ericyoungberg** [comment]
We can't allow duplicate tables exist since data-browser pulls in every table available. That will be misleading when looking for datasets and duplicates of the same one are shown to the user. We should have the script drop a table if necessary and then recreate it if the sync fails.

**Comment by mzagaja** [comment]
Annoyingly the problem is Carto does not have an API for dropping a table. I have to drop the entire DB and rebuild it from scratch, or manually remove it in the Carto UI. If I manually remove it in the Carto UI then the name remains reserved and it still gets an underscore suffix. The only way to surmount this I have found so far is to drop and rebuild the entire DB to get it to restart.

**Comment by ericyoungberg** [comment]
Okay, I'll try to come up with something then on the frontend. It would just be a shame to store all of those duplicate datasets.

**Comment by mzagaja** [comment]
Once the next DataCommon dev cycle budget opens up I think we can put some time behind figuring out how to wrangle the duplicates on the back-end. Or if we stick with the hosted solution we presumably could file a support ticket once in a while and ask the engineers at Carto to take care of that.

In hosted Carto, from my experience, there currently isn't a way to surmount the `_number` append if you try a sync that fails. For the most part I do not think we'll actually get duplicate datasets, there will just be ones that failed the first time for some reason and then work the second time. So it will have an underscore since the first table name was reserved but not actually be duplicate of another live/working dataset.

**Comment by ericyoungberg** [comment]
It is possible to drop tables in the Carto API https://gis.stackexchange.com/questions/202253/carto-import-api-create-delete-datasets

**Comment by ericyoungberg** [comment]
So we should refactor the code to drop the table if it fails syncing and then attempt a resync.

**Comment by mzagaja** [comment]
It might be worth a try. While it would take care of the small number of actual duplicate datasets, I think it might not solve the underscore issue. My experience so far has been that once some import has been attempted and fails, the name remains reserved. Subsequent import/sync add attempts append the underscore. My suspicion is that this is due to the sync record still existing even after deleting the actual import. However I have not teased out the exact nuances of this behavior so if you want to take a run at it, go for it.

**Comment by ericyoungberg** [comment]
This will probably do the trick for removing the underscore https://carto.com/docs/carto-engine/import-api/sync-tables/#removing-the-synchronization-feature-from-a-given-dataset

**Comment by mzagaja** [comment]
@ericyoungberg I spot checked this today and noticed that for the few datasets that present this issue, the original datasets are all there. In many cases, these are larger data sets. So I think what is happening is that CartoDB receives the original request to sync the table. The original request takes a long time to slurp the table though. So then it receives request 2 and the original request is not yet in the list of sync'd tables and it attempts to do it again. So then we have two tables. One has a _1 underscore. This can easily be fixed with some manual cleanup given the small number that exist (6).

Alternative options can include spreading out our import requests to give Carto more time to catch up on all our sync requests, or upgrading to a larger instance. We can also explore keeping a local text file list of sync'd datasets and then just referencing that instead of Carto itself. However, then we have another mini database to keep in sync.

This also may not be likely to occur again in the future since we're not flooding Carto with so many requests the way we do when we add tons of datasets.

I think the best course of action here is manual delete the six, wait and see if the script tries to re-add them, and then wait and see if it occurs again. If it persists then we can also consider creating a "vacuum" script to remove the `_1` datasets using the two HTTP requests you found above.

**Comment by arouault** [comment]
@ericyoungberg please recap the meeting direction from Susan and offer Matt some pointers on how best to implement.

**Comment by ericyoungberg** [comment]
Done
