### ISSUE TITLE
Download not reflecting changes

### ISSUE THREAD

**Issue by theryankelly** [MAPC/datacommon#396]
Moving Slack thread from #datacommon to here.

Currently tables [437](https://datacommon.mapc.org/browser/datasets/437) Population by Race, Ethnicity, and Age 2020 (Municipality); [431](https://datacommon.mapc.org/browser/datasets/431) Population by Race, Ethnicity, and Age (Hispanic only) 2020 (Municipality); [425](https://datacommon.mapc.org/browser/datasets/425) Population and Housing Unit Changes 2010-2020 (Municipal). These tables have been updated but changes are not being reflected as cache may need to be cleared.

The change we are looking for is the addition of regional summaries (muni ID 352 and up) being populated in the csv download.

Will need to clear `public/cache`
Also need to document the process as our caching process has previously been an issue, added in with a limited budget at the time.

**Comment by TarinAComer** [comment]
The files were deleted from the cache and regenerated.

[tabular.census2020_2010_pop_hu_change_m.csv](https://github.com/MAPC/datacommon/files/7990072/tabular.census2020_2010_pop_hu_change_m.csv)
[tabular.census2020_pl94_hisp_by_race_age_m.csv](https://github.com/MAPC/datacommon/files/7990073/tabular.census2020_pl94_hisp_by_race_age_m.csv)
[tabular.census2020_pl94_race_age_m.csv](https://github.com/MAPC/datacommon/files/7990074/tabular.census2020_pl94_race_age_m.csv)

The README has been updated.
