### ISSUE TITLE
Some tables fail to sync

### ISSUE THREAD

**Issue by mzagaja** [MAPC/datacommon#54]
A bunch of tables fail to sync properly for unknown reasons. Their sync will crash Carto:

```
tables_to_skip = ["b17026_income_to_poverty_by_families_acs_ct",
                  "b18101_disability_by_gender_age_acs_ct",
                  "b19001_hh_income_acs_ct",
                  "b08134_means_by_traveltime_to_work_acs_bg",
                  "b18135_health_insurance_by_disability_status_acs_ct",
                  "b19037_hh_income_by_age_race_acs_ct",
                  "b07403_geomobility_out_migration_acs_m",
                  "b08303_traveltime_to_work_by_residence_acs_m",
                  "b08006_means_transportation_to_work_by_residence_gender_acs_ct",
                  "b25046_b25044_b01003_hh_vehicle_ownership_acs_m",
                  "b25002_b25003_hu_occupancy_by_tenure_race_acs_bg",
                  "b23025_employment_acs_ct",
                  "b11007_hh_with_seniors_acs_ct",
                  "b22002_hh_foodstamps_snap_hhtype_kids_acs_m",
                  "demo_race_latino_detail_ct",
                  "b17001_poverty_by_age_gender_acs_m"]
```

**Comment by arouault** [comment]
These tables failed to sync over to Carto. Erroring is minimal.

**Comment by mzagaja** [comment]
Just manually sent a sync request for `b17026_income_to_poverty_by_families_acs_ct` and it worked fine. I think we manually do these one by one to confirm but it is possible that carto was getting overloaded based on sequence of the imports or some other external factor.

**Comment by mzagaja** [comment]
`b18101_disability_by_gender_age_acs_ct` is good

**Comment by mzagaja** [comment]
`b19001_hh_income_acs_ct` is good

**Comment by mzagaja** [comment]
`b08134_means_by_traveltime_to_work_acs_bg` put Carto on the struggle bus. Going to let it fight through it for an hour or so.

**Comment by mzagaja** [comment]
`"b18135_health_insurance_by_disability_status_acs_ct"` also seems to fail. Some things I do not think are the culprit:

1. Table size. The above table is only 2.6MB and larger tables are in the database.
2. Permissions on the viewer account. I can login to the database server and see this table manually in Postico.
3. System resources. CPU is not maxing out and we still have 5GB of HDD space internally.

**Comment by mzagaja** [comment]
It turns out if you enter tmux copy mode then resque just freezes/hangs tight until you exit tux copy mode and let things return to normal so `b18135_health_insurance_by_disability_status_acs_ct` now imported fine.

**Comment by mzagaja** [comment]
`b19037_hh_income_by_age_race_acs_ct` is good to go

**Comment by mzagaja** [comment]
`b07403_geomobility_out_migration_acs_m` is good to go

**Comment by mzagaja** [comment]
`b08303_traveltime_to_work_by_residence_acs_m` is good to go

**Comment by mzagaja** [comment]
`b08006_means_transportation_to_work_by_residence_gender_acs_ct` is good to go

**Comment by mzagaja** [comment]
`b25046_b25044_b01003_hh_vehicle_ownership_acs_m` is good to go

**Comment by mzagaja** [comment]
`b25002_b25003_hu_occupancy_by_tenure_race_acs_bg` is good to go

**Comment by mzagaja** [comment]
`b23025_employment_acs_ct` is good to go

**Comment by mzagaja** [comment]
`b11007_hh_with_seniors_acs_ct` is good to go

**Comment by mzagaja** [comment]
```
"b22002_hh_foodstamps_snap_hhtype_kids_acs_m",
 "demo_race_latino_detail_ct",
"b17001_poverty_by_age_gender_acs_m"
```
Are all good. So at this point we only have one stubborn table that wouldn't go. I'm going to submit a PR to remove the ones that worked from the suppression list. My best guess is these failed initially doing to some server overload.
