### ISSUE TITLE
View geospatial data in tabular form

### ISSUE THREAD

**Issue by ericyoungberg** [MAPC/datacommon#70]
Now that you can find the data, you should be able to enter the page where the data should be fetched  by the current Ember code. If it doesn't, then you're going to have to figure out why.

Once the data is loading in, we need to filter out any column from the view that contains data of unreasonable size. This will most likely only be the `the_geom` column which contains the actual geospatial components of the data. Everything else associated with that geometry should be human digestible and displayed to the user. 

We are not viewing the data on a map in this phase because we haven't designed the UX/UI for it along with the constraint of not building any new major features in the databrowser during Phase 1. 

- [x] Ensure the geospatial data loads and populates the table
- [x] Filter out any massive columns from the view

**Comment by mzagaja** [comment]
I think this is largely resolved by https://github.com/MAPC/databrowser/blob/5100c342c42d7a1b1cdb3e936fb96e528abe98f8/app/routes/datasets.js#L59-L68
