### ISSUE TITLE
Download geospatial data/metadata

### ISSUE THREAD

**Issue by ericyoungberg** [MAPC/datacommon#72]
There are already some links to download data and they may work out of the box since Carto is currently handling the file encoding. Outside of the file encoding, we must include the geospatial metadata with each datafile, regardless of the datafile's format. This will probably be in the form of two files being downloaded simultaneously. 

- [x] Ensure Carto can encode the data into Shapefile, GeoJSON, and CSV
- [x] Download metadata in CSV format alongside the data download

**Comment by mzagaja** [comment]
This seems to be resolved by https://github.com/MAPC/databrowser/commit/5c148b04caea4b54818aaea9618f295db5aac9f9
