### ISSUE TITLE
Change data browser table categories to reflect updated categories

### ISSUE THREAD

**Issue by arouault** [MAPC/datacommon#77]
Change names to what they're supposed to be in the data browser table.

**Comment by mzagaja** [comment]
Updated per Susan in Slack: https://mapc.slack.com/archives/C1DDA1MKQ/p1533072929000106

> The _data_browser table now has a menu1 topic: Popular Datasets with a few tables

> I also expanded on some of the source column names so they are written out, not just acronyms
such as ACS and CHAS
