### ISSUE TITLE
Feature to Show Recent Datasets

### ISSUE THREAD

**Issue by mzagaja** [MAPC/datacommon#79]
As a user I would like to be able to show recent datasets. This would enable us to show what was recently updated or is new.

**Comment by iangmhill** [comment]
Icons for the popular and recent datasets:
![data browser](https://user-images.githubusercontent.com/6565554/43220075-1060d53c-9017-11e8-92b8-23b12ba0096f.png)

**Comment by mzagaja** [comment]
Susan has implemented this manually through her `_data_browser` table as seen at https://staging.datacommon.mapc.org/browser/Popular%20Datasets
